#!/bin/bash

code --install-extension esbenp.prettier-vscode ;
code --install-extension dbaeumer.vscode-eslint ;
code --install-extension eamodio.gitlens ;
code --install-extension ms-python.python ;
code --install-extension eamodio.gitlens ;
code --install-extension PKief.material-icon-theme ;
code --install-extension zhuangtongfa.material-theme ;
code --install-extension naumovs.color-highlight ;
code --install-extension ms-python.vscode-pylance ;
code --install-extension ritwickdey.LiveServer ;
code --install-extension VisualStudioExptTeam.vscodeintellicode ;
code --install-extension formulahendry.auto-rename-tag ;
code --install-extension formulahendry.auto-close-tag ;
code --install-extension christian-kohler.npm-intellisense ;
code --install-extension aaron-bond.better-comments ;
code --install-extension tht13.html-preview-vscode ;
code --install-extension xabikos.JavaScriptSnippets ;
code --install-extension abusaidm.html-snippets ;
