#!/bin/bash

while true; do
    read -p "Do you want to remotely connect to your WORKSTATION ? [Y/n] " yn
    case $yn in
        [Yy]* ) 

            read -p "Enter Remote Desktop USER: PCS\\" -i gabriel.silva -e REMOTE_USER ; echo  
            read -p "Enter Remote Desktop PASSWORD: " REMOTE_PASSWORD ; echo  
            read -p "Enter Remote Desktop IP: " REMOTE_IP ; echo  
            xfreerdp /u:"PCS\\$REMOTE_USER" /p:$REMOTE_PASSWORD /v:$REMOTE_IP /sound:sys:pulse /microphone:sys:pulse /w:1888 /h:994; break;;

        [Nn]* )

            read -p "Enter Remote Desktop USER: " REMOTE_USER ; echo  
            read -p "Enter Remote Desktop PASSWORD: " REMOTE_PASSWORD ; echo  
            read -p "Enter Remote Desktop IP: " REMOTE_IP ; echo  
            xfreerdp /u:$REMOTE_USER /p:$REMOTE_PASSWORD /v:$REMOTE_IP /sound:sys:pulse /microphone:sys:pulse /w:1888 /h:994; break;;

        * ) echo "Please answer with Y[es] or N[o].";;
    esac
done
